image:
  repository: artifactory.dagility.com/docker/vdcheckghasdf-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdcheckghasdf-backend-dagility-preprod.dagility.com
    paths:
    - /
serviceAccount:
  create: false
